name: build
on: 
  workflow_dispatch:
  push:
    branches:
      - vue3

env:
  NODE_VERSION: 20

jobs:
  windows:
    name: "Build SCRCPY+ for Windows"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm i
        working-directory: app
      - name: Build
        run: npm run electron:build
        working-directory: app
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: electron_dist
